#server.port=5001
#spring.datasource.username=root
#spring.datasource.password=jinli666
#spring.datasource.url=jdbc:mysql://localhost:3306/nkuser0?autoReconnect=true&serverTimezone=UTC&useSSL=true&useUnicode=true&characterEncoding=utf-8
#spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
#
##spring.mvc.view.prefix=/WEB-INF/
##spring.mvc.view.suffix=.jsp
#spring.mvc.view.prefix= /
#spring.mvc.view.suffix= .jsp
#
#mybatis:
#mapper-locations: classpath:com/nk/mapper/*Mapper.xml
#type-aliases-package: com.nk.entity
#configuration:
#map-underscore-to-camel-case: true
#log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper:
#auto-dialect: oracle
#support-methods-arguments: true
#reasonable: true
#
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.nologging.NoLoggingImpl
#
#
#
spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nkuser0?autoReconnect=true&serverTimezone=UTC&useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: jinli666
  mvc:
    view:
      prefix: /
      suffix: .jsp
  redis:
    database: 0
    timeout: 5000
    host: 123.56.220.62
    port: 6379
mybatis:
  mapper-locations: classpath:com/nk/mapper/*Mapper.xml
  type-aliases-package: com.nk.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 5001
